const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  loadConfig: () => ipcRenderer.invoke('load-config'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  loadResults: () => ipcRenderer.invoke('load-results'),
  saveResults: (results) => ipcRenderer.invoke('save-results', results),
  loadCreatedSites: (options) => ipcRenderer.invoke('load-created-sites', options || {}),
  saveCreatedSites: (sites) => ipcRenderer.invoke('save-created-sites', sites),
  upsertCreatedSite: (entry) => ipcRenderer.invoke('upsert-created-site', entry),
  deleteCreatedSite: (id) => ipcRenderer.invoke('delete-created-site', id),
  syncCreatedSites: () => ipcRenderer.invoke('sync-created-sites'),
  cloudflareSaveSite: (project) => ipcRenderer.invoke('cloudflare-save-site', project || {}),
  loadGeneratedTokens: () => ipcRenderer.invoke('load-generated-tokens'),
  saveGeneratedTokens: (tokens) => ipcRenderer.invoke('save-generated-tokens', tokens),
  selectOutputDir: () => ipcRenderer.invoke('select-output-dir'),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  listFolderFiles: (folder) => ipcRenderer.invoke('list-folder-files', folder),
  getFileStat: (filePath) => ipcRenderer.invoke('get-file-stat', filePath),
  selectFile: (filters) => ipcRenderer.invoke('select-file', filters),
  selectFiles: (options) => ipcRenderer.invoke('select-files', options || {}),
  validateZipIndex: (zipPath) => ipcRenderer.invoke('validate-zip-index', zipPath),
  readTextFile: (filePath) => ipcRenderer.invoke('read-text-file', filePath),
  startRun: (config) => ipcRenderer.invoke('start-run', config),
  pauseRun: () => ipcRenderer.invoke('pause-run'),
  resumeRun: () => ipcRenderer.invoke('resume-run'),
  stopRun: () => ipcRenderer.invoke('stop-run'),
  checkIndex: (options) => ipcRenderer.invoke('check-index', options || {}),
  checkSitesIndex: (options) => ipcRenderer.invoke('check-sites-index', options || {}),
  reinjectIndex: (options) => ipcRenderer.invoke('reinject-index', options || {}),
  generateTokens: (options) => ipcRenderer.invoke('generate-tokens', options),
  stopTokenGen: () => ipcRenderer.invoke('stop-token-gen'),
  crawlSiteUrls: (options) => ipcRenderer.invoke('crawl-site-urls', options),
  submitNaverCollect: (options) => ipcRenderer.invoke('submit-naver-collect', options),
  stopCrawl: () => ipcRenderer.invoke('stop-crawl'),
  recordNetlifyFlowStart: (options) => ipcRenderer.invoke('record-netlify-flow-start', options),
  recordNetlifyFlowStop: () => ipcRenderer.invoke('record-netlify-flow-stop'),
  onLogLine: (callback) => ipcRenderer.on('log-line', (_, line) => callback(line)),
  onJobProgress: (callback) => ipcRenderer.on('job-progress', (_, data) => callback(data)),
  onResultsUpdated: (callback) => ipcRenderer.on('results-updated', (_, data) => callback(data)),
  onSitesUpdated: (callback) => ipcRenderer.on('sites-updated', (_, data) => callback(data)),
  onTokenGenLog: (callback) => ipcRenderer.on('token-gen-log', (_, line) => callback(line)),
  onTokenGenProgress: (callback) => ipcRenderer.on('token-gen-progress', (_, data) => callback(data)),
  onCrawlUrlLog: (callback) => ipcRenderer.on('crawl-url-log', (_, line) => callback(line)),
  onNaverCollectProgress: (callback) => ipcRenderer.on('naver-collect-progress', (_, data) => callback(data)),
  onIndexUpdated: (callback) => ipcRenderer.on('index-updated', (_, data) => callback(data)),
  onIndexProgress: (callback) => ipcRenderer.on('index-progress', (_, data) => callback(data)),
  onSitesIndexUpdated: (callback) => ipcRenderer.on('sites-index-updated', (_, data) => callback(data)),
  onSitesIndexProgress: (callback) => ipcRenderer.on('sites-index-progress', (_, data) => callback(data)),
  onReinjectLog: (callback) => ipcRenderer.on('reinject-log', (_, line) => callback(line)),
  offLogLine: (callback) => ipcRenderer.removeListener('log-line', (_, line) => callback(line)),
  kkangPing: () => ipcRenderer.invoke('kkang-ping'),
  kkangListKeywords: () => ipcRenderer.invoke('kkang-list-keywords'),
  kkangAddKeywords: (items) => ipcRenderer.invoke('kkang-add-keywords', { items }),
  kkangRemoveKeywords: (keywords) => ipcRenderer.invoke('kkang-remove-keywords', { keywords }),
  kkangGenerate: (job) => ipcRenderer.invoke('kkang-generate', job),
  kkangStop: () => ipcRenderer.invoke('kkang-stop'),
  kkangRetryNaver: (options) => ipcRenderer.invoke('kkang-retry-naver', options || {}),
  kkangRetryNaverIndex: (options) => ipcRenderer.invoke('kkang-retry-naver-index', options || {}),
  naverSessionStatus: () => ipcRenderer.invoke('naver-session-status'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  clipboardWrite: (text) => ipcRenderer.invoke('clipboard-write', text),
  naverSessionStart: (options) => ipcRenderer.invoke('naver-session-start', options || {}),
  naverSessionRefreshSites: () => ipcRenderer.invoke('naver-session-refresh-sites'),
  onNaverSessionUpdate: (callback) => ipcRenderer.on('naver-session-update', (_, data) => callback(data)),
  focusMainWindow: () => ipcRenderer.invoke('focus-main-window'),
  sendHotkey: (hotkey) => ipcRenderer.invoke('send-hotkey', hotkey || {}),
  netlifyCreditsLogin: (options) => ipcRenderer.invoke('netlify-credits-login', options || {}),
  netlifyCreditsRefresh: (options) => ipcRenderer.invoke('netlify-credits-refresh', options || {}),
  netlifyCreditsStatus: () => ipcRenderer.invoke('netlify-credits-status'),
  netlifyCreditsStop: () => ipcRenderer.invoke('netlify-credits-stop'),
  onNetlifyCreditsUpdate: (callback) => ipcRenderer.on('netlify-credits-update', (_, data) => callback(data)),
  onKkangLog: (callback) => ipcRenderer.on('kkang-log', (_, line) => callback(line)),
  captchaLearnStats: () => ipcRenderer.invoke('captcha-learn-stats'),
  captchaLearnTrain: () => ipcRenderer.invoke('captcha-learn-train'),
  onCaptchaLearnLog: (callback) => ipcRenderer.on('captcha-learn-log', (_, line) => callback(line)),
  dothomeSignup: (options) => ipcRenderer.invoke('dothome-signup', options || {}),
  dothomeSignupStop: () => ipcRenderer.invoke('dothome-signup-stop'),
  dothomeSeoGenerate: (options) => ipcRenderer.invoke('dothome-seo-generate', options || {}),
  dothomeDeploy: (options) => ipcRenderer.invoke('dothome-deploy', options || {}),
  onDothomeLog: (callback) => ipcRenderer.on('dothome-log', (_, line) => callback(line)),
  dothomeMailSessionStatus: () => ipcRenderer.invoke('dothome-mail-session-status'),
  dothomeMailSessionLogin: (options) => ipcRenderer.invoke('dothome-mail-session-login', options || {}),
  dothomeMailSessionClose: () => ipcRenderer.invoke('dothome-mail-session-close'),
  onDothomeMailSessionUpdate: (callback) => ipcRenderer.on('dothome-mail-session-update', (_, data) => callback(data)),
});
